spring:
  datasource:
    url: "jdbc:mysql://localhost:3310/schedule?useUnicode=true&characterEncoding=utf-8"
    username: "root"
    password: "root"
  jpa:
    generate-ddl: true
    show-sql: true
    properties:
      hibernate:
        dialect: "org.hibernate.dialect.MySQL57Dialect"
    hibernate:
      ddl-auto: "create-drop"

  # 上传文件大小限制
  servlet:
    multipart:
      enabled: true
      max-file-size: ${file.size:20MB}
      max-request-size: ${file.size:20MB}

